name: Balancer
description: Budget manager for roommates.
publish_to: 'none'


version: 1.0.1+2

environment:
  sdk: '>=3.0.5 <4.0.0'


dependencies:
  flutter:
    sdk: flutter

  cloud_firestore: ^4.4.5
  firebase_auth: ^4.7.1
  firebase_core: ^2.8.0
  firebase_storage: ^11.0.16
  firebase_messaging: ^14.3.0
  flutter_local_notifications: ^15.1.0+1
  shared_preferences: ^2.0.15
  cupertino_icons: ^1.0.2
  device_preview: ^1.1.0
  package_info_plus: ^3.1.2
  font_awesome_flutter: ^10.1.0
  rxdart: ^0.27.7
  image_picker: ^0.8.5+3
  permission_handler: ^10.0.0
  google_fonts: ^4.0.4
  multi_value_listenable_builder: ^0.0.2
  syncfusion_flutter_datepicker: ^22.2.5
  percent_indicator: ^4.0.1
  
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.2.0
  json_serializable: ^6.3.1
  flutter_launcher_icons: ^0.11.0

flutter:
  uses-material-design: true

  assets:
    - assets/

flutter_icons:
  android: true
  ios: true
  image_path: "assets/logo.png"
  adaptive_icon_foreground: "assets/logo_foreground.png"
  adaptive_icon_background: "#cccccc"